### PR TITLE
Update README.md with latest release

### PR DESCRIPTION
**Pull request by digitalbuddha**
@jaredsburrows  all set

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@digitalbuddha Thanks!

So you are able to push locally but not with gradle?

I see this is version `0.1.0`, https://mvnrepository.com/artifact/com.github.brianPlummer/tinydancer/0.1.0. In gradle it is set to `1.0.0-SNAPSHOT`: https://github.com/friendlyrobotnyc/TinyDancer/blob/master/build.gradle#L39.

**Comment by digitalbuddha** [comment]
I think @brianPlummer pushed manually using a local gradle.properties. We tried to redo the keys and no bueno.  I need to learn more about the process or just grab someone else that know what they are doing.

**Comment by jaredsburrows** [comment]
@digitalbuddha Alright. You could PM me the pass, I could tinker with it and then you can change the password after. Let me know if I can help.

**Comment by jaredsburrows** [comment]
@digitalbuddha Oh, I just meant you can message me on hangouts or email: jaredsburrows@gmail.com.

**Pull request merged**
